### PR TITLE
Add styles for visited links #129

### PR DESCRIPTION
**Pull request by paulradzkov**
Added styles for visited links and better styles for focused links.

### CODE REVIEW

**Comment by paulradzkov** [comment]
Preview https://paulradzkov-forks.github.io/this-is-responsive/resources.html

**Comment by bradfrost** [comment]
Hey @paulradzkov,
Thanks for this proposed change. As nice as it is, I'm going to stick with the current design, which intentionally downplays the visual treatment of the recommended resources.

**Comment by paulradzkov** [comment]
@bradfrost What about visited links? Do you need separate PR with visited links only?

**Comment by bradfrost** [comment]
@paulradzkov that would be great, thanks!

**Pull request closed without merging**
